{{- $fullName := include "helm.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ trim .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deploymentPort | default 80 }}
              protocol: TCP
          command: ["npm", "run", "start:prod"]
          {{- if .Values.env }}
          env:
            {{- if .Values.env.configMap}}
            {{- range $key, $val := .Values.env.configMap }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name:  {{ $fullName }}-configmap
                  key: {{ $key }}
            {{- end }}
            {{- end }}
            {{- if .Values.env.secrets}}
            {{- range $key,$value := .Values.env.secrets}}
            - name: {{ $value }}
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-secrets
                  key: {{ $value }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- if eq .Values.disableHealthProbes false }}
          {{- if .Values.readinessProbe }}