kafka:
  name: fc
  version: 3.9.0
  annotations:
    strimzi.io/kraft: disabled
    strimzi.io/node-pools: disabled
  replicas: 3
  resources: {}
  listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
      authentication:
        type: tls
  storage:
    type: persistent-claim
    size: 100Gi
    deleteClaim: true
  jvmOptions:
    xms: 3092m
    xmx: 3092m
    metaspaceSize: 96m
    maxGCPauseMillis: 20
    initiatingHeapOccupancyPercent: 35
    g1HeapRegionSize: 16M
    minMetaspaceFreeRatio: 50
    maxMetaspaceFreeRatio: 80
    useG1GC: true
zookeeper:
  replicas: 3
  resources: {}
  storage:
    type: persistent-claim
    size: 100Gi
    deleteClaim: true

# have a separated controller and broker nodepools
separatedPools: true
# ------
# lower envs pool
combinedPool:
  name: fc-combinedPool
  replicas: 3
  storage:
    volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
# ------
# prod pools
controllerPool:
  name: fc-controllerpool
  replicas: 3
  storage:
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
brokerPool:
  name: fc-brokerpool
  replicas: 3
  storage:
    volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false