{{- if .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nifi-external-secrets
  labels:
    app: {{ include "apache-nifi.name" . | quote }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: nifi-external-secrets
    creationPolicy: Owner
  data:
    # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
    {{- range $key, $value  := .Values.externalSecrets }}
    - secretKey: {{ $value }}
      remoteRef:
        key: {{ $key }}
    {{- end }}
{{- end }}