{{ if .Values.env }}
{{- if .Values.env.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nextjs.fullname" . }}-configmap
data:
  {{- with .Values.env.configMap }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{ end }}
{{ end  }}