apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.limacharlie.agent.name }}-license"
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-store
    kind: ClusterSecretStore
  target:
    name: "{{ .Values.limacharlie.agent.name }}-license"
    creationPolicy: Owner
  data:
    - secretKey: license
      remoteRef:
        key: LIMACHARLIELICENSE
