apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ .Values.limacharlie.agent.name }}-agent"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.limacharlie.agent.name }}
spec:
  selector:
    matchLabels:
      name: "{{ .Values.limacharlie.agent.name }}-agent"
  template:
    metadata:
      labels:
        name: "{{ .Values.limacharlie.agent.name }}-agent"
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: {{ .Values.limacharlie.agent.name }}
          image: {{ .Values.sensor.image }}
          env:
            - name: LC_INSTALLATION_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.limacharlie.agent.name }}-license"
                  key: license
            - name: LC_TAGS
              value: {{ .Values.sensor.tags | quote }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: proc
              mountPath: /proc
            - name: sys
              mountPath: /sys
            - name: etc
              mountPath: /etc
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: etc
          hostPath:
            path: /etc
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet